<?php
require dirname(__DIR__, 3) . '/include/cp_header.php';
xoops_cp_header();
?>
<style type="text/css" media="screen">
    <?php include '.././inc_files/share.css'; ?>
</style>
<table width="100%" border="0" cellspacing="0" cellpadding="0" height="100%">
<tr>
<td align="center" valign="middle">
<table class="forminput" width="63" border="0" cellspacing="0" cellpadding="5" bgcolor="white">
<tr>
<td nowrap bgcolor="#ccccff" align="center">
<font color="#ff9900">вз</font> ╜ш═¤╖ы▓╠ <font color="#ff9900">вз</font>
</td>
</tr>
<tr>
<td nowrap><?=$result_stat?></td>
</tr>
</table>
<p>
<a href="admin.php">╠сды</a>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td align="center" valign="middle"><hr size="1"><?=$footer?><hr size="1"></td>
</tr>
</table>
</td>
</tr>
</table>
<?php
xoops_cp_footer();
?>
