<?php
require __DIR__ . '/header.php';
require XOOPS_ROOT_PATH.'/header.php';
?>
<style type="text/css" media="screen">
    <?php include 'inc_files/share.css'; ?>
</style>
<table width="100%" border="0" cellspacing="0" cellpadding="0" height="100%">
<tr>
<td align="center" valign="middle">
<table class="forminput" width="63" border="0" cellspacing="0" cellpadding="5" bgcolor="white">
<tr>
<td nowrap bgcolor="#ccccff" align="center">
<font color="#ff9900">¢§</font> ½èÍý·ë²Ì <font color="#ff9900">¢§</font>
</td>
</tr>
<tr>
<td nowrap><?=$result_stat?></td>
</tr>
</table>
<p>
<a href="index.php">·Ç¼¨ÈÄ¤ËÌá¤ë</a>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td align="center" valign="middle"><hr size="1"><?=$footer?><hr size="1"></td>
</tr>
</table>
</td>
</tr>
</table>
<?php
require XOOPS_ROOT_PATH.'/footer.php';
?>
